#import <React/RCTBridgeModule.h>
#import <React/RCTBridge.h>
#import <React/RCTEventDispatcher.h>

@interface RCT_EXTERN_MODULE(RNThinkingAnalyticsModule, NSObject)

RCT_EXTERN_METHOD(init:(NSDictionary *)options libVersion:(NSString *)libVersion)
RCT_EXTERN_METHOD(track:(NSDictionary *)options)
RCT_EXTERN_METHOD(trackUpdate:(NSDictionary *)options)
RCT_EXTERN_METHOD(trackOverwrite:(NSDictionary *)options)
RCT_EXTERN_METHOD(trackFirstEvent:(NSDictionary *)options)
RCT_EXTERN_METHOD(timeEvent:(NSDictionary *)options)
RCT_EXTERN_METHOD(login:(NSDictionary *)options)
RCT_EXTERN_METHOD(logout:(NSDictionary *)options)
RCT_EXTERN_METHOD(userSet:(NSDictionary *)options)
RCT_EXTERN_METHOD(userUnset:(NSDictionary *)options)
RCT_EXTERN_METHOD(userSetOnce:(NSDictionary *)options)
RCT_EXTERN_METHOD(userAdd:(NSDictionary *)options)
RCT_EXTERN_METHOD(userDel:(NSDictionary *)options)
RCT_EXTERN_METHOD(userAppend:(NSDictionary *)options)
RCT_EXTERN_METHOD(userUniqAppend:(NSDictionary *)options)
RCT_EXTERN_METHOD(setSuperProperties:(NSDictionary *)options)
RCT_EXTERN_METHOD(unsetSuperProperty:(NSDictionary *)options)
RCT_EXTERN_METHOD(clearSuperProperties:(NSDictionary *)options)
RCT_EXTERN_METHOD(identify:(NSDictionary *)options)
RCT_EXTERN_METHOD(flush:(NSDictionary *)options)
RCT_EXTERN_METHOD(enableAutoTrack:(NSDictionary *)options)
RCT_EXTERN_METHOD(calibrateTime:(NSDictionary *)options)
RCT_EXTERN_METHOD(calibrateTimeWithNtp:(NSDictionary *)options)
RCT_EXTERN_METHOD(enableThirdPartySharing:(NSDictionary *)options)
RCT_EXTERN_METHOD(setTrackStatus:(NSDictionary *)options)
RCT_EXTERN_METHOD(getPresetProperties:(NSDictionary *)options resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(getSuperProperties:(NSDictionary *)options resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(getDistinctId:(NSDictionary *)options resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(getAccountId:(NSDictionary *)options resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(getDeviceId:(NSDictionary *)options resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(trackViewScreen:(NSDictionary *)options)
RCT_EXTERN_METHOD(trackViewClick:(nonnull NSNumber *)viewId)
RCT_EXTERN_METHOD(saveViewProperties:(nonnull NSNumber *)viewId title:(NSString *)title viewProperties:(NSDictionary *)viewProperties)
RCT_EXTERN_METHOD(saveRootViewProperties:(nonnull NSNumber *)viewId title:(NSString *)title viewProperties:(NSDictionary *)viewProperties rootTag:(nonnull NSNumber *)rootTag)
RCT_EXTERN_METHOD(getStorageItem:(NSString *)key resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
RCT_EXTERN_METHOD(setStorageItem:(NSString *)key value:(NSString *)value resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)

@end
